<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInitf77cd79a6a3ca39d0df98056181456e7
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('file.php' === $class) {
            require __DIR__ . 'file.php';
        }
    }

    /**
     * @return \Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . 'file.php';

        spl_autoload_register(array('file.php', 'file.php'), true, true);
        self::$loader = $loader = new \Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('file.php', 'file.php'));

        require __DIR__ . 'file.php';
        call_user_func(\Composer\Autoload\ComposerStaticInitf77cd79a6a3ca39d0df98056181456e7::getInitializer($loader));

        $loader->register(true);

        $filesToLoad = \Composer\Autoload\ComposerStaticInitf77cd79a6a3ca39d0df98056181456e7::$files;
        $requireFile = \Closure::bind(static function ($fileIdentifier, $file) {
            if (empty($GLOBALS['file.php'][$fileIdentifier])) {
                $GLOBALS['file.php'][$fileIdentifier] = true;

                require $file;
            }
        }, null, null);
        foreach ($filesToLoad as $fileIdentifier => $file) {
            $requireFile($fileIdentifier, $file);
        }

        return $loader;
    }
}
